#!/usr/bin/env node
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { join } from 'node:path'
import { PRESETS, paletteFor, parseHex, readableOnWhite, themeCss, toHex } from '../frontend/src/lib/palette.js'
import { InputEnded, createPrompter, style } from './lib/prompt.mjs'
import { keychain, keychainAvailable } from './lib/keychain.mjs'
import { readEnv, writeEnv } from './lib/envfile.mjs'
import {
  ManagementError, TOKEN_PAGE, apiKeysPage, management, pickKeys, planAuthChanges, projectRef, urlConfigPage,
} from './lib/management.mjs'
import { API_PORT, DEV_PORT, PREVIEW_PORT } from '../frontend/ports.mjs'
import { copiedUsers, supabaseAdmin } from './lib/stack.mjs'

const ROOT = fileURLToPath(new URL('..', import.meta.url))
const BRAND_FILE = join(ROOT, 'frontend/src/brand.json')
const THEME_FILE = join(ROOT, 'frontend/src/styles/theme.css')
const FAVICON_FILE = join(ROOT, 'frontend/public/favicon.svg')
const CLIENT_ENV = join(ROOT, 'frontend/.env')
const SERVER_ENV = join(ROOT, 'backend/.env')
const SERVER_TEMPLATE = join(ROOT, 'backend/.env.example')

const DEV_ORIGIN = `http://localhost:${DEV_PORT}`
const PREVIEW_ORIGIN = `http://localhost:${PREVIEW_PORT}`
const STORED_KEYS = ['SUPABASE_URL', 'SUPABASE_PUBLISHABLE_KEY', 'SUPABASE_SECRET_KEY']
const PROJECT_URL = /^https:\/\/[a-z0-9-]+\.supabase\.co\/?$/

const CLIENT_HEADER = [
  '# Written by scripts/setup.mjs. Read by Vite; only VITE_ values reach the browser.',
  '# Rebuild from the keychain with: node scripts/setup.mjs sync',
]
const SERVER_HEADER = [
  '# Written by scripts/setup.mjs from backend/.env.example. Read by the API and docker compose.',
  '# SUPABASE_SECRET_KEY can change any account; the API only reads users with it. It never reaches the browser.',
]

const say = (...lines) => console.log(lines.join('\n'))
const heading = text => say('', style.bold(text), style.dim('─'.repeat(text.length)))

function loadBrand() {
  return JSON.parse(readFileSync(BRAND_FILE, 'utf8'))
}

function saveBrand(brand) {
  writeFileSync(BRAND_FILE, JSON.stringify(brand, null, 2) + '\n')
}

function slugify(name) {
  return name.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'login-page'
}

function ensureSlug(brand) {
  if (!brand.slug) {
    brand.slug = slugify(brand.name || 'login-page')
    saveBrand(brand)
  }
  return brand.slug
}

function vault(brand) {
  return keychain(ensureSlug(brand), brand.name || 'Login page')
}

function escapeXml(s) {
  return s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' })[c])
}

function faviconSvg(name, accentHex) {
  const palette = paletteFor(accentHex)
  const letter = ([...name.trim()][0] || '•').toUpperCase()
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
  <rect width="24" height="24" rx="6" fill="${palette['--accent']}"/>
  <text x="12" y="16.6" text-anchor="middle" font-family="Poppins, Inter, Arial, sans-serif" font-weight="700" font-size="14" fill="${palette['--on-accent']}">${escapeXml(letter)}</text>
</svg>
`
}

function writeTheme(brand) {
  writeFileSync(THEME_FILE, `/* Generated by scripts/setup.mjs from the accent in frontend/src/brand.json. Re-run setup to change it. */\n${themeCss(brand.accent)}`)
  writeFileSync(FAVICON_FILE, faviconSvg(brand.name, brand.accent))
}

function showPalette(accentHex) {
  const p = paletteFor(accentHex)
  const chip = key => `${style.swatch(parseHex(p[key]))} ${style.dim(key.replace('--', ''))}`
  say(`  ${chip('--accent')}  ${chip('--accent-h')}  ${chip('--accent-t')}  ${chip('--ink')}`)
  if (!readableOnWhite(accentHex)) {
    say(style.yellow('  White text is hard to read on this colour, so buttons will use dark text instead.'))
  }
}

async function chooseColour(prompt, current) {
  say('', 'Colour theme:')
  PRESETS.forEach((preset, i) => {
    say(`  ${String(i + 1).padStart(2)}  ${style.swatch(parseHex(preset.hex))}  ${preset.name.padEnd(9)} ${style.dim(preset.hex)}`)
  })
  say(`  ${String(PRESETS.length + 1).padStart(2)}        Custom ${style.dim('(any hex colour, e.g. #0E7490)')}`)

  const currentPreset = PRESETS.findIndex(p => p.hex.toUpperCase() === String(current).toUpperCase())
  const fallback = currentPreset >= 0 ? String(currentPreset + 1) : current

  for (;;) {
    const answer = await prompt.ask(`Pick 1-${PRESETS.length + 1}, a name, or a hex`, fallback)
    const byNumber = PRESETS[Number(answer) - 1]
    const byName = PRESETS.find(p => p.name.toLowerCase() === answer.toLowerCase())
    if (byNumber || byName) return (byNumber || byName).hex
    if (Number(answer) === PRESETS.length + 1) {
      const hex = await prompt.ask('Hex colour')
      if (parseHex(hex)) return toHex(parseHex(hex))
    } else if (parseHex(answer)) {
      return toHex(parseHex(answer))
    }
    say(style.red('  That is not one of the options or a hex colour like #2563EB.'))
  }
}

async function runBrand(prompt) {
  heading('Brand')
  const brand = loadBrand()
  const currentName = brand.configured ? brand.name : ''

  let name = ''
  while (!name) {
    name = (await prompt.ask('App name', currentName)).slice(0, 40).trim()
    if (!name) say(style.red('  A name is required. It appears on the sign-in page and in the browser tab.'))
  }

  const accent = await chooseColour(prompt, brand.accent || PRESETS[0].hex)
  say('')
  showPalette(accent)

  brand.name = name
  brand.accent = accent
  brand.configured = true
  ensureSlug(brand)
  saveBrand(brand)
  writeTheme(brand)

  say('', style.green(`✓ ${name} with accent ${accent}`),
    style.dim('  wrote frontend/src/brand.json, frontend/src/styles/theme.css and frontend/public/favicon.svg'),
    style.dim('  edit headline, blurb and highlights in frontend/src/brand.json to change the sign-in copy'))
  return brand
}

function currentValues(brand) {
  const client = readEnv(CLIENT_ENV)
  const server = readEnv(SERVER_ENV)
  const box = vault(brand)
  return {
    url: client.VITE_SUPABASE_URL || server.SUPABASE_URL || box.get('SUPABASE_URL') || '',
    publishable: client.VITE_SUPABASE_PUBLISHABLE_KEY || box.get('SUPABASE_PUBLISHABLE_KEY') || '',
    secret: server.SUPABASE_SECRET_KEY || box.get('SUPABASE_SECRET_KEY') || '',
  }
}

function refFromUrl(url) {
  return /^https:\/\/([a-z0-9-]+)\.supabase\.co/.exec(url ?? '')?.[1] ?? null
}

async function askToken(prompt) {
  if (process.env.SUPABASE_ACCESS_TOKEN) {
    say(style.dim('Using SUPABASE_ACCESS_TOKEN from the environment.'))
    return process.env.SUPABASE_ACCESS_TOKEN.trim()
  }
  say(
    'A personal access token lets setup find your project, fetch its keys and set the redirect URLs.',
    style.dim(`Create one at ${TOKEN_PAGE}. It is used for this run only and never written to disk.`),
  )
  return prompt.askHidden('Access token (blank to paste the keys by hand)')
}

async function chooseProject(prompt, api, currentRef) {
  const projects = await api.projects()
  if (!projects?.length) {
    say(style.yellow('That account has no projects. Create one at https://supabase.com/dashboard, then run setup again.'))
    return null
  }
  say('', 'Projects:')
  projects.forEach((p, i) => {
    const status = p.status === 'ACTIVE_HEALTHY' ? '' : style.yellow(`  ${p.status ?? ''}`)
    say(`  ${String(i + 1).padStart(2)}  ${p.name}  ${style.dim(`${projectRef(p)} · ${p.region ?? ''}`)}${status}`)
  })
  const currentIndex = projects.findIndex(p => projectRef(p) === currentRef)
  const fallback = currentIndex >= 0 ? String(currentIndex + 1) : projects.length === 1 ? '1' : ''

  for (;;) {
    const answer = await prompt.ask(`Project 1-${projects.length}`, fallback)
    const project = projects[Number(answer) - 1] || projects.find(p => projectRef(p) === answer)
    if (project) {
      if (project.status && project.status !== 'ACTIVE_HEALTHY') {
        say(style.yellow(`  ${project.name} is ${project.status}. Restore it in the dashboard if sign-in fails.`))
      }
      return project
    }
    say(style.red('  Pick one of the numbers above.'))
  }
}

async function askProductionUrl(prompt, siteUrl) {
  const current = siteUrl && !/localhost/.test(siteUrl) ? siteUrl : ''
  for (;;) {
    const answer = (await prompt.ask('Production URL, if this will be deployed (blank to skip)', current)).replace(/\/+$/, '')
    if (!answer || /^https?:\/\/[^\s/]+(\/\S*)?$/.test(answer)) return answer
    say(style.red('  Use a full URL like https://app.example.com'))
  }
}

async function configureAuth(prompt, api, project) {
  const ref = projectRef(project)
  const current = await api.authConfig(ref)
  const production = await askProductionUrl(prompt, current.site_url)
  const redirectUrls = [`${DEV_ORIGIN}/**`, `${PREVIEW_ORIGIN}/**`, ...(production ? [`${production}/**`] : [])]

  let inviteOnly = false
  if (!current.disable_signup) {
    say(style.dim('This page has no sign-up form, but Supabase still accepts sign-ups while they are enabled.'))
    inviteOnly = await prompt.confirm('Turn off public sign-ups so accounts are invitation-only?', true)
  }

  const { changes, added } = planAuthChanges(current, { redirectUrls, siteUrl: production || DEV_ORIGIN, inviteOnly })
  if (!Object.keys(changes).length) {
    say(style.green('✓ Auth settings already allow this app’s redirect URLs.'))
    return
  }

  say('', `Changes to ${project.name} auth settings:`)
  if (added.length) say(`  redirect URLs  + ${added.join('\n                 + ')}`)
  if (changes.site_url) say(`  site URL       ${current.site_url || '(unset)'} → ${changes.site_url}`)
  if (changes.disable_signup) say('  sign-ups       enabled → disabled')

  if (!(await prompt.confirm('Apply these changes?', true))) {
    say(style.dim(`  Skipped. Add them by hand at ${urlConfigPage(ref)}`))
    return
  }
  await api.updateAuthConfig(ref, changes)
  say(style.green('✓ Auth settings updated.'))
}

async function fetchFromManagementApi(prompt, token, current) {
  const api = management(token)
  const project = await chooseProject(prompt, api, refFromUrl(current.url))
  if (!project) return null
  const ref = projectRef(project)

  const keys = pickKeys(await api.apiKeys(ref))
  if (!keys.publishable) {
    say(style.yellow(`${project.name} has no publishable key yet. Create one at ${apiKeysPage(ref)}`))
    keys.publishable = await askPublishable(prompt, current.publishable)
  }
  if (!keys.secret) {
    say(style.yellow(`${project.name} has no secret key yet. Create one at ${apiKeysPage(ref)}; the API needs it to copy users.`))
    keys.secret = await askSecret(prompt, current.secret)
  }
  say(style.green(`✓ Fetched the project URL and keys for ${project.name}.`))

  try {
    await configureAuth(prompt, api, project)
  } catch (e) {
    say(style.yellow(`Could not update the auth settings: ${e.message}`),
      style.dim(`  Add ${DEV_ORIGIN}/** and ${PREVIEW_ORIGIN}/** at ${urlConfigPage(ref)}`))
  }
  return { url: `https://${ref}.supabase.co`, ...keys }
}

async function askPublishable(prompt, current) {
  for (;;) {
    const value = await prompt.ask('Publishable key (sb_publishable_...)', current)
    if (value.startsWith('sb_publishable_')) return value
    if (value.startsWith('sb_secret_')) say(style.red('  That is the secret key. The browser gets the publishable one.'))
    else say(style.red('  Publishable keys start with sb_publishable_. Legacy anon keys are not supported.'))
  }
}

async function askSecret(prompt, current) {
  for (;;) {
    const value = await prompt.askHidden(`Secret key, sb_secret_... (hidden${current ? ', blank keeps current' : ', blank to skip'})`)
    if (!value) return current || ''
    if (value.startsWith('sb_secret_')) return value
    say(style.red('  Secret keys start with sb_secret_. Legacy service_role keys are not supported.'))
  }
}

async function enterByHand(prompt, current) {
  say('', `Find these at ${apiKeysPage(refFromUrl(current.url))}`)
  let url = ''
  while (!url) {
    const value = (await prompt.ask('Project URL (https://<ref>.supabase.co)', current.url)).replace(/\/+$/, '')
    if (PROJECT_URL.test(value)) url = value
    else say(style.red('  That does not look like https://<project-ref>.supabase.co'))
  }
  const publishable = await askPublishable(prompt, current.publishable)
  const secret = await askSecret(prompt, current.secret)

  say('', style.yellow('Add these redirect URLs under Authentication → URL Configuration,'),
    style.yellow('or password reset and invitation links will not come back to this app:'),
    `  ${DEV_ORIGIN}/**`, `  ${PREVIEW_ORIGIN}/**`, style.dim(`  ${urlConfigPage(refFromUrl(url))}`))
  return { url, publishable, secret }
}

function store(brand, values) {
  const box = vault(brand)
  if (keychainAvailable) {
    const saved = []
    if (values.url && box.set('SUPABASE_URL', values.url)) saved.push('SUPABASE_URL')
    if (values.publishable && box.set('SUPABASE_PUBLISHABLE_KEY', values.publishable)) saved.push('SUPABASE_PUBLISHABLE_KEY')
    if (values.secret && box.set('SUPABASE_SECRET_KEY', values.secret)) saved.push('SUPABASE_SECRET_KEY')
    say(style.green(`✓ Stored ${saved.join(', ')} in the login keychain`), style.dim(`  as ${box.describe()}`))
  }
  writeEnvFiles(values)
}

function writeServerEnv(entries) {
  const template = existsSync(SERVER_TEMPLATE) ? readFileSync(SERVER_TEMPLATE, 'utf8') : ''
  writeEnv(SERVER_ENV, entries, [...SERVER_HEADER, '', ...template.replace(/\n$/, '').split('\n')])
}

function writeEnvFiles(values) {
  writeEnv(CLIENT_ENV, {
    VITE_SUPABASE_URL: values.url,
    VITE_SUPABASE_PUBLISHABLE_KEY: values.publishable,
  }, CLIENT_HEADER)
  say(style.green('✓ Wrote frontend/.env'))
  writeServerEnv({ SUPABASE_URL: values.url, SUPABASE_SECRET_KEY: values.secret })
  say(style.green('✓ Wrote backend/.env') + (values.secret
    ? style.dim(' (with the secret key, mode 600, gitignored)')
    : style.yellow(' without a secret key: the API will not start until it has one')))
}

async function offerFirstUser(prompt, values) {
  if (!values.secret) return
  if (!(await prompt.confirm('Create an account in Supabase to sign in with now?', false))) return

  const email = (await prompt.ask('Email')).trim()
  if (!email) return
  const fullName = (await prompt.ask('Full name', email.split('@')[0])).trim()
  let password = ''
  while (!password) {
    const first = await prompt.askHidden('Password (at least 8 characters)')
    const again = await prompt.askHidden('Repeat password')
    if (first.length < 8) say(style.red('  Too short.'))
    else if (first !== again) say(style.red('  Those did not match.'))
    else password = first
  }

  try {
    const user = await supabaseAdmin(values.url, values.secret).create(email, password, fullName)
    say(style.green(`✓ Created ${user.email} in Supabase Auth. Sign in with it once the app is running.`))
  } catch (e) {
    say(style.red(`  Could not create ${email}: ${e.message}`))
  }
}

function nextSteps() {
  say('', style.bold('Next:'),
    '  docker compose up -d --build --wait      Postgres, the API and the web app',
    `  open http://localhost:${PREVIEW_PORT}               sign in`,
    style.dim(`  or cd frontend && npm run dev for hot reload on http://localhost:${DEV_PORT}, against the API in Docker`),
    style.dim('  Add more people in the Supabase dashboard under Authentication → Users; the API copies them into Postgres.'))
}

async function runSupabase(prompt, brand = loadBrand()) {
  heading('Supabase')
  const current = currentValues(brand)

  let values = null
  const token = await askToken(prompt)
  if (token) {
    try {
      values = await fetchFromManagementApi(prompt, token, current)
    } catch (e) {
      if (e instanceof InputEnded) throw e
      const reason = e instanceof ManagementError && e.status === 401 ? 'That access token was not accepted.' : e.message
      say(style.red(reason), 'Falling back to entering the values by hand.')
    }
  }
  if (!values) values = await enterByHand(prompt, current)

  say('')
  store(brand, values)
  await offerFirstUser(prompt, values)
  return values
}

function runSync({ quiet = false } = {}) {
  const brand = loadBrand()
  if (!keychainAvailable) {
    if (!quiet) say('sync needs the macOS keychain. Run node scripts/setup.mjs supabase instead.')
    return false
  }
  const box = vault(brand)
  const values = {
    url: box.get('SUPABASE_URL'),
    publishable: box.get('SUPABASE_PUBLISHABLE_KEY'),
    secret: box.get('SUPABASE_SECRET_KEY'),
  }
  if (!values.url || !values.publishable) {
    if (!quiet) say(`Nothing stored for ${box.describe()}. Run node scripts/setup.mjs supabase first.`)
    return false
  }
  writeEnvFiles(values)
  return true
}

function runStatus() {
  const brand = loadBrand()
  const client = readEnv(CLIENT_ENV)
  const server = readEnv(SERVER_ENV)
  const mark = ok => (ok ? style.green('set    ') : style.dim('--     '))

  heading('Brand')
  say(`  ${mark(brand.configured)} ${brand.configured ? `${brand.name} · ${brand.accent}` : 'not configured (node scripts/setup.mjs brand)'}`)

  heading('Files')
  say(`  ${mark(client.VITE_SUPABASE_URL)} frontend/.env  VITE_SUPABASE_URL ${style.dim(client.VITE_SUPABASE_URL || '')}`)
  say(`  ${mark(client.VITE_SUPABASE_PUBLISHABLE_KEY)} frontend/.env  VITE_SUPABASE_PUBLISHABLE_KEY`)
  say(`  ${mark(server.SUPABASE_URL)} backend/.env   SUPABASE_URL`)
  say(`  ${mark(server.SUPABASE_SECRET_KEY)} backend/.env   SUPABASE_SECRET_KEY`)

  heading('Stack')
  const copied = copiedUsers(ROOT)
  say(copied === null
    ? `  ${mark(false)} database not up yet ${style.dim('(docker compose up -d --build --wait)')}`
    : `  ${mark(true)} ${copied} Supabase user${copied === 1 ? '' : 's'} copied into app.supabase_user ${style.dim(`(API on http://localhost:${API_PORT})`)}`)

  heading('Keychain')
  if (!keychainAvailable) return say('  not in use (needs macOS; SETUP_NO_KEYCHAIN turns it off)')
  const box = vault(brand)
  for (const key of STORED_KEYS) say(`  ${mark(box.get(key))} ${key}`)
  say(style.dim(`  ${box.describe()}`))
}

function runForget(keys) {
  const box = vault(loadBrand())
  const targets = keys.includes('all') ? STORED_KEYS : keys
  if (!targets.length) return say(`Name the keys to forget, or all: ${STORED_KEYS.join(', ')}`)
  for (const key of targets) say(box.remove(key) ? `removed ${key}` : `not stored: ${key}`)
}

function needs() {
  const brand = loadBrand()
  const client = readEnv(CLIENT_ENV)
  const server = readEnv(SERVER_ENV)
  return {
    brand: !brand.configured,
    supabase: !client.VITE_SUPABASE_URL || !client.VITE_SUPABASE_PUBLISHABLE_KEY || !server.SUPABASE_URL,
  }
}

async function runIfNeeded() {
  const need = needs()
  if (!need.brand && !need.supabase) return
  if (need.supabase && !need.brand && runSync({ quiet: true })) {
    say(style.dim('setup: rebuilt frontend/.env and backend/.env from the keychain'))
    return
  }
  if (!process.stdin.isTTY) {
    say(style.yellow('setup: this app is not configured yet. Run node scripts/setup.mjs in a terminal.'))
    return
  }
  say(style.bold('This app has not been set up yet.'))
  await runAll(need)
}

async function runAll(need = { brand: true, supabase: true }) {
  const prompt = createPrompter()
  try {
    const brand = need.brand ? await runBrand(prompt) : loadBrand()
    if (need.supabase) await runSupabase(prompt, brand)
    nextSteps()
  } finally {
    prompt.close()
  }
}

async function withPrompt(step) {
  const prompt = createPrompter()
  try {
    await step(prompt)
  } finally {
    prompt.close()
  }
}

function usage() {
  say(`Sets up the brand and the Supabase environment for the app and its API.

  node scripts/setup.mjs                    name, colour theme, then Supabase
  node scripts/setup.mjs brand              just the name and colour theme
  node scripts/setup.mjs supabase           just the Supabase URL, keys and auth settings
  node scripts/setup.mjs sync               rebuild frontend/.env and backend/.env from the keychain
  node scripts/setup.mjs status             what is configured (never prints secrets)
  node scripts/setup.mjs forget <KEY|all>

With an access token (prompted, or SUPABASE_ACCESS_TOKEN) setup lists your projects,
fetches the publishable and secret keys and adds this app's redirect URLs. Without one
it asks for the values instead. Set SETUP_NO_KEYCHAIN=1 to skip the macOS keychain.`)
}

const [command, ...rest] = process.argv.slice(2)

try {
  switch (command) {
    case undefined: await runAll(); break
    case '--if-needed': await runIfNeeded(); break
    case 'brand': await withPrompt(runBrand); break
    case 'supabase': await withPrompt(prompt => runSupabase(prompt)); break
    case 'sync': process.exitCode = runSync() ? 0 : 1; break
    case 'status': runStatus(); break
    case 'forget': runForget(rest); break
    case 'help': case '-h': case '--help': usage(); break
    default: say(`Unknown command: ${command}`, ''); usage(); process.exitCode = 1
  }
} catch (e) {
  console.error(style.red(`setup: ${e.message}`))
  process.exitCode = 1
}
